name = "tuanph-com"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

routes = [
  { pattern = "tuanph.com/*", zone_name = "tuanph.com" }
]

[observability]
enabled = true
